'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HabboFreedom.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _26097_jacket_M_general() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_26097_jacket_M_general", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _26705_hat_U_general() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_26705_hat_U_general", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _33229_acc_face_U_veil() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_33229_acc_face_U_veil", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _39730_hat_U_ridhel() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_39730_hat_U_ridhel", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _50491_hh_human_acc_face() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_50491_hh_human_acc_face", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _50491_hh_human_hats() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_50491_hh_human_hats", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _50519_hat_U_fez() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_50519_hat_U_fez", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _50537_trousers_U_camo() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_50537_trousers_U_camo", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _50539_hat_U_armyhelmet() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_50539_hat_U_armyhelmet", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _50542_hat_U_nycop() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_50542_hat_U_nycop", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _52216_jacket_U_camo() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_52216_jacket_U_camo", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _58272_acc_chest_U_medal2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_58272_acc_chest_U_medal2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _58272_acc_chest_U_medal3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_58272_acc_chest_U_medal3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _58320_hat_U_camocap() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_58320_hat_U_camocap", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _58320_hat_U_kevlar() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_58320_hat_U_kevlar", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _58407_acc_chest_U_rank1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_58407_acc_chest_U_rank1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _58407_acc_chest_U_rank2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_58407_acc_chest_U_rank2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _58407_acc_chest_U_rank3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_58407_acc_chest_U_rank3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _58407_acc_chest_U_rank4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_58407_acc_chest_U_rank4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _58407_acc_chest_U_rank5() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_58407_acc_chest_U_rank5", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _58481_jacket_U_kevlar() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_58481_jacket_U_kevlar", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _58611_hat_U_napkin() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_58611_hat_U_napkin", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _58617_acc_chest_U_medal1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_58617_acc_chest_U_medal1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _58618_hat_U_military() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_58618_hat_U_military", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _59888_shirt_M_camotank() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_59888_shirt_M_camotank", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _61408_jacket_F_military() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_61408_jacket_F_military", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _61408_jacket_M_military() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_61408_jacket_M_military", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _63025_acc_face_U_wedveil() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_63025_acc_face_U_wedveil", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _64082_acc_chest_U_bulletbelt() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_64082_acc_chest_U_bulletbelt", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _64460_jacket_F_regiment() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_64460_jacket_F_regiment", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _64460_jacket_M_regiment() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_64460_jacket_M_regiment", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _65554_acc_head_U_grandheadjewel() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_65554_acc_head_U_grandheadjewel", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _65554_shirt_F_grandsherwani() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_65554_shirt_F_grandsherwani", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _65554_shirt_F_sherwani() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_65554_shirt_F_sherwani", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _65554_shirt_M_grandsherwani() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_65554_shirt_M_grandsherwani", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _65554_shirt_M_sherwani() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_65554_shirt_M_sherwani", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _65573_hat_U_turban() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_65573_hat_U_turban", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _65574_acc_head_U_headjewel() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_65574_acc_head_U_headjewel", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _65574_hat_U_monkeyfezhat() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_65574_hat_U_monkeyfezhat", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _65583_shirt_U_grandsari() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_65583_shirt_U_grandsari", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _65588_hair_U_jewelbraidhair() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_65588_hair_U_jewelbraidhair", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _65633_hat_U_studentcap() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_65633_hat_U_studentcap", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _66116_acc_face_U_nyfacemask1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_66116_acc_face_U_nyfacemask1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _66116_acc_face_U_nyfacemask2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_66116_acc_face_U_nyfacemask2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _66116_acc_face_U_nyfacemask3_swf() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_66116_acc_face_U_nyfacemask3_swf", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _66116_acc_face_U_nyfacemask4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_66116_acc_face_U_nyfacemask4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _66116_acc_face_U_nyfacemask5() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_66116_acc_face_U_nyfacemask5", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _66116_acc_face_U_nyfacemask6() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_66116_acc_face_U_nyfacemask6", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _66116_acc_face_U_nyfacemask7() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_66116_acc_face_U_nyfacemask7", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _66116_acc_face_U_nyfacemask8() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_66116_acc_face_U_nyfacemask8", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _66174_hat_U_camohat() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_66174_hat_U_camohat", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _66174_hat_U_hijab() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_66174_hat_U_hijab", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _66174_trousers_U_camojoggers() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_66174_trousers_U_camojoggers", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _66210_jacket_F_camohoodie() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_66210_jacket_F_camohoodie", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _66210_jacket_M_camohoodie() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_66210_jacket_M_camohoodie", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _66210_shirt_F_camocroptop() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_66210_shirt_F_camocroptop", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _66210_shirt_M_camocroptop() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_66210_shirt_M_camocroptop", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
